a = float(input())
b = float(input())
c = float(input())
d = float(input())
e = float(input())
f = float(input())
y = (e * c - a * f) / (b * c - a * d)
x = (f * b - d * e) / (b * c - a * d)
print(x, '', y)
